spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sdw
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect